const express = require('express');
const cors = require('cors');
const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const app = express();
app.use(cors());
app.use(express.json());

// Path to the SQLite database generated by the Python scraper
const dbPath = path.join(__dirname, '../Scraper/news_pulse.db');
const db = new sqlite3.Database(dbPath, (err) => {
    if (err) {
        console.error("Database connection error:", err.message);
    } else {
        console.log("Backend successfully connected to Python SQLite Database!");
    }
});

// API Endpoint to send news articles to the React Frontend
app.get('/api/news', (req, res) => {
    const sql = "SELECT * FROM news ORDER BY created_at DESC";
    db.all(sql, [], (err, rows) => {
        if (err) {
            res.status(500).json({ error: err.message });
            return;
        }
        res.json({ news: rows });
    });
});

const PORT = 5000;
app.listen(PORT, () => {
    console.log(`Backend server is running on http://localhost:${PORT}`);
});
